# -*- mode: python -*-

Import("env")

env.Library(
    target="migration",
    source=[
        "migrate_cmd.cpp",
        "Migrator.cpp",
        "MigratorLock.cpp",
        "Registry.cpp"
    ],
    LIBDEPS=[],
)